---
title: "First Exercises"
author: "Caio César Albuquerque"
date: '2022-08-31'
output:
  html_document:
    df_print: paged
  
---

```{r}
library(mlr3)
library(tidyverse)
library(ggplot2)
```


### Exercicios
```{r}
link <- "https://raw.githubusercontent.com/jacobwright32/Web_Scraper_AI_Core_Project/bb4865ae568e23ab8fadb6ea58cf117df2164ef3/web%20scraping/Cleaned%20Data/Brazil_Sao%20Bernardo%20Do%20Campo_Cleaned.csv"

dados <- readr::read_csv(link)
```


### Criando função para coletar 1000 amostras e calcular a média de humidity
```{r}
nova_funcao <- function(){
  
  dados %>% 
    sample_n(1000) %>% 
    summarise(humidity = mean(humidity)) %>% 
    pluck("humidity")
  
}

# Usar a função
nova_funcao()


# A função "pluck()" extrai o(s) valor(es) de um determinado vetor 
```


### Repetir a função anterior 1000 vezes
```{r}
for (i in 1:1000) {
  print(nova_funcao())
}
```


### Tidyverse manner para repetir a função 1000 vezes
```{r}
experimento <- 1:1000 %>% 
  map_dbl(~ nova_funcao())

# Plotando o histograma das médias
as.data.frame(experimento) %>%
  ggplot() + geom_histogram(aes(experimento), colour = "black", fill = "orange")


# A função "map_dbl()" é utilizada para dados numéricos
```



```{r}
modelo <- dados %>% lm(humidity ~ wind_speed + cloud_coverage + pressure, data = .)

# Salvar predição como variável (vetor no banco de dados chamado "dados")
dados$predicao <- predict(modelo)

modelo <- lm(rnorm(100) ~ rnorm(100))
summary(modelo)$r.squared
```






















